version: "3"
services:
        web:
            image: richarvey/nginx-php-fpm:latest
            privileged: true
            ports:
                    - "3005:80"
            volumes:
                    - ./www:/var/www/html
            networks:
                - default
